//! Upload one or more images into a writable directory link, each with a 400×400
//! webp thumbnail (downscaled to 200×200 if over 100 KiB). Thumbnails are
//! generated by decoding the image (limits disabled so huge images work); the
//! source bytes are dropped before the upload, which then streams from disk.
//!
//!   cargo run -p peergos-fs --example upload_images -- <base> <link> [img ...]

use image::DynamicImage;
use peergos_core::mutable::HttpMutablePointers;
use peergos_core::{ContentAddressedStorage, HttpStorage, ReqwestPoster};
use std::fs::File;
use std::sync::Arc;

const THUMBNAIL_SIZE: u32 = 400;
const THUMBNAIL_DOWNSCALE: u32 = 200;
const THUMBNAIL_MAX_BYTES: usize = 100 * 1024;

/// Decode an image with allocation limits disabled (huge images allowed).
fn decode(bytes: &[u8]) -> Option<DynamicImage> {
    let mut reader = image::ImageReader::new(std::io::Cursor::new(bytes))
        .with_guessed_format()
        .ok()?;
    reader.no_limits();
    reader.decode().ok()
}

/// Center-cropped square webp thumbnail (scale the short edge to `size`, crop).
fn center_crop_webp(img: &DynamicImage, size: u32) -> Vec<u8> {
    let (w, h) = (img.width(), img.height());
    let tall = h > w;
    let canvas_w = if tall { size } else { w * size / h };
    let canvas_h = if tall { h * size / w } else { size };
    let resized = img.resize_exact(canvas_w, canvas_h, image::imageops::FilterType::Triangle);
    let x = if tall { 0 } else { (canvas_w - size) / 2 };
    let y = if tall { (canvas_h - size) / 2 } else { 0 };
    let rgba = resized.crop_imm(x, y, size, size).to_rgba8();
    webp::Encoder::from_rgba(rgba.as_raw(), size, size).encode(80.0).to_vec()
}

fn make_thumbnail(bytes: &[u8]) -> Option<(String, Vec<u8>)> {
    let img = decode(bytes)?;
    let big = center_crop_webp(&img, THUMBNAIL_SIZE);
    let data = if big.len() > THUMBNAIL_MAX_BYTES {
        center_crop_webp(&img, THUMBNAIL_DOWNSCALE)
    } else {
        big
    };
    Some(("image/webp".to_string(), data))
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = std::env::args().collect();
    let base = args.get(1).cloned().unwrap_or_else(|| "http://localhost:7777/".to_string());
    let link = args.get(2).cloned().expect("need a writable dir link");
    let home = std::env::var("HOME").unwrap_or_default();
    let paths: Vec<String> = if args.len() > 3 {
        args[3..].to_vec()
    } else {
        ["huge.jpg", "climbing-koonya.jpg", "mandelbrot.png", "s-sword.png", "boom-boom-cliff.jpeg"]
            .iter()
            .map(|f| format!("{home}/Downloads/{f}"))
            .collect()
    };

    let poster = Arc::new(ReqwestPoster::new(&base, false)?);
    let store: Arc<dyn ContentAddressedStorage> = Arc::new(HttpStorage::new(poster.clone(), true));
    let mutable = HttpMutablePointers::new(poster);

    // Follow the link node to the real writable directory + recover its signer.
    let mut entry = peergos_fs::retrieve_secret_link_capability(&link, store.as_ref(), None).await?;
    let (_n, props) = peergos_fs::retrieve_file_metadata(&entry, store.clone(), &mutable).await?;
    if props.is_link {
        entry = peergos_fs::list_directory(&entry, store.clone(), &mutable)
            .await?
            .into_iter()
            .next()
            .ok_or("link node has no target")?
            .cap;
    }
    let signer = peergos_fs::recover_signer(&entry, store.clone(), &mutable).await?;

    for path in &paths {
        let name = std::path::Path::new(path).file_name().unwrap().to_string_lossy().to_string();
        let size = match std::fs::metadata(path) {
            Ok(m) => m.len(),
            Err(_) => {
                println!("skip {name}: not found");
                continue;
            }
        };
        println!("\n=== {name} ({size} bytes) ===");

        // Generate the thumbnail from the file, then drop the source bytes so the
        // streaming upload doesn't hold the whole file in memory.
        let thumbnail = {
            let bytes = std::fs::read(path)?;
            match make_thumbnail(&bytes) {
                Some((m, d)) => {
                    let td = image::load_from_memory(&d)?;
                    println!("  thumbnail: {m}, {}x{}, {} bytes", td.width(), td.height(), d.len());
                    Some((m, d))
                }
                None => {
                    println!("  WARNING: could not decode for a thumbnail!");
                    None
                }
            }
        };
        if thumbnail.is_none() {
            return Err(format!("{name} did not produce a thumbnail").into());
        }

        let path2 = path.clone();
        let cap = peergos_fs::upload_file_streaming(
            &entry,
            &name,
            size,
            thumbnail,
            Some(signer.clone()),
            None,
            move || File::open(&path2),
            store.clone(),
            &mutable,
        )
        .await?;

        // Verify from the server: thumbnail present + dimensions, mime, writable.
        let (_node, stored) = peergos_fs::retrieve_file_metadata(&cap, store.clone(), &mutable).await?;
        let (tw, th, tbytes) = match &stored.thumbnail {
            Some((_m, d)) => {
                let ti = image::load_from_memory(d)?;
                (ti.width(), ti.height(), d.len())
            }
            None => (0, 0, 0),
        };
        println!(
            "  stored: mime={} writable={} thumbnail={}x{} ({} bytes)",
            stored.mime_type,
            cap.is_writable(),
            tw,
            th,
            tbytes
        );
        assert!(tbytes > 0, "{name} stored without a thumbnail!");
    }

    println!("\nDirectory now contains:");
    for e in peergos_fs::list_directory(&entry, store, &mutable).await? {
        println!("  {} {}", if e.is_dir == Some(true) { "[dir ]" } else { "[file]" }, e.name);
    }
    Ok(())
}
